### ISSUE TITLE
[Feature request] Do not download videos that are already present

### ISSUE THREAD

**Issue by MohamedIM** [althonos/InstaLooter#15]
For images it only downloads new ones however in videos (when using -v option) it is not the case it always tries to download all of them however it fails (throwing exception) as all of them are already downloaded.

**Comment by althonos** [comment]
Hi there ! Yes, this is due to the fact that to get the actual video file, one has to load an additional page whereas pictures are available directly on the profile / hashtag page.

To fix that, two choices:
- renaming files to their media id so that no other page has to be loaded
- load the video page to check the real file name.

**Comment by althonos** [comment]
So I chose the second option, hopefully it won't add too much time (at least it will be faster to check a name than to redownload a video). You can try the latest GitHub version, it should work faster.

Right now, only the video name is checked. I may add a check for filesize later if needed.
