### ISSUE TITLE
usercache protocol error

### ISSUE THREAD

**Issue by igmanbe** [althonos/InstaLooter#151]
I've updated today [March 25th, 2018] InstaLooter and I'm getting the next error:

File "/Library/Python/2.7/site-packages/fs/opener/registry.py", line 75, in get_opener
    "protocol '{}' is not supported".format(protocol)
fs.opener.errors.UnsupportedProtocol: protocol 'usercache' is not supported

I'm runing it in a OSX High Sierra with python 2.7

**Comment by althonos** [comment]
It looks like you're using an older version of Pyfilesystem2, but that's strange considering I pinned the minimal version to make sure UserCache is supported.

Try updating fs : 
```
pip install -U fs
```

**Comment by igmanbe** [comment]
I'm using fs (2.0.20) I think it is the latest one

**Comment by althonos** [comment]
It is the latest version indeed. Does running
```
python2 -c "import fs; fs.open_fs('usercache://')"
```
in a terminal give you the same error ?

**Comment by igmanbe** [comment]
yes, it is giving this error:

python -c "import fs; fs.open_fs('usercache://')" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/fs/opener/registry.py", line 179, in open_fs
    default_protocol=default_protocol
  File "/Library/Python/2.7/site-packages/fs/opener/registry.py", line 136, in open
    opener = self.get_opener(protocol)
  File "/Library/Python/2.7/site-packages/fs/opener/registry.py", line 75, in get_opener
    "protocol '{}' is not supported".format(protocol)
fs.opener.errors.UnsupportedProtocol: protocol 'usercache' is not supported

**Comment by althonos** [comment]
Then it looks like a `Pyfilesystem` bug... Have you tried updating `setuptools` ? I implemented a loader that uses `pkg_resources`, so maybe the older version does not work well.

**Comment by igmanbe** [comment]
I have the last version of setuptools. I tried uninstalling fs and installing a previous version and it still gives me the same error...

**Comment by althonos** [comment]
@willmcgugan: you may be interested in this

@igmanbe: the only reason this is failing is because `fs.opener` does not find the entry point, which is given by `pkg_resources`. Can you give me the output of:
```
 python -c "import pkg_resources; print([x.name for x in pkg_resources.iter_entry_points('fs.opener')])"
```
please ?

**Comment by igmanbe** [comment]
I think I've solved the problem upgrading distribute package (pip install --upgrade distribute). Now the exit of output you asked for is:

python -c "import pkg_resources; print([x.name for x in pkg_resources.iter_entry_points('fs.opener')])"
['ftp', 'osfs', 'usercache', 'temp', 'tar', 'userdata', 'mem', 'sitedata', 'file', 'userconf', 'userlog', 'zip', 'siteconf']

Thank you very much

**Comment by althonos** [comment]
Great ! I'll propose a PR to `fs` to add a minimal `distribute` version then.

**Comment by Henning-K** [comment]
This issue is present again for me after update to instalooter 2.3.4

System:
Ubuntu 18.04.2 LTS

Python3 --version:
3.6.7

fs version:
2.4.4

Tried uninstalling and re-installing instalooter, issue still persists.

Any and all instalooter commands just return:
2019-03-xx [...] instalooter.cli[106xx] CRITICAL protocol 'usercache' is not supported

**Comment by Henning-K** [comment]
Ran `pip3 uninstall fs` which removed fs:2.4.4 and then tried again.
Suddenly instalooter commands started working again.
Ran `pip3 show fs` since I didn't expect there to actually be an installed version of fs left on my machine. Color me surprised to see that version 2.1.2 is (still) installed.
Had to run `pip3 uninstall fs` a bunch more times until there were no more different versions of it installed on my PC.
THEN ran `pip3 install fs` again which installed fs:2.4.4.
THEN tried instalooter commands again, which then worked with the intended most recent version of fs.

Earlier, I had not thought about going this elaborate route since I ran the `install -I fs`, `install --force-reinstall fs` and even the uninstall+install routine on fs before, not imagining that 'reinstall' or 'force reinstall' does not include getting rid of old versions installed on the system

FFS, pip dependency management is a dumpster fire...

PS: This issue can be closed again.

**Comment by althonos** [comment]
This can happen if you have both a local (`pip install --user`) and a global (`pip install`) setup for the same library, you then need to uninstall a few times, since `pip` will only uninstall the first one it finds.
But yeah, `pip` is nice when you develop libraries, but it is definitely not great when you need a complete stack for a particular program.
