### ISSUE TITLE
[Feature request] stop downloading files if they are found in the destination folder

### ISSUE THREAD

**Issue by mrgloom** [althonos/InstaLooter#16]
Are already downloaded images skipped at second time? I tried to download photos from same user 2 times, seems download time is the same, so as I understand photos not skipped, but downloaded twice and overwritten?

**Comment by althonos** [comment]
Hi there !
Well, what takes time with InstaLooter is downloading files, but iterating through all pages. Even If InstaLooter skips downloading some medias, it'll have to load all pages to make sure it doesn't forget any file.

Since Instagram must have an anti-DDoS policy, let's say a request takes around 500ms: for an account with ~2200 pictures, then InstaLooter will have to load 2200 / 12 = 184 pages, so you'll have to wait 184*0.5s = 1m32s.

Would it help if I added a `--new` flag to the CLI, to stop fetching medias after the first already downloaded file is encountered ?

**Comment by mrgloom** [comment]
Yes, I think it would be helpfull.

You will compare images by name or by hash stroring some meta info about images?

p.s. in what order photos appear in folder, I mean what their names mean? As I understand sorting by name for now break the original order in what photos were posted?

**Comment by disrupted** [comment]
> Would it help if I added a --new flag to the CLI, to stop fetching medias after the first already downloaded file is encountered ?

very helpful indeed

**Comment by althonos** [comment]
1. Concerning the names, I have no idea but those are the actually names they bear on the instagram. #14 is about customizing names, I'll get to that at some point.

2. I'll check to see if Instagram holds the hash of the picture/video in the metadata. If they do, i'll use it to check duplication; else, maybe a byte-size comparison instead.

3. If you want to sort by post order, you can use the `--add-metadata` flag and then sort by date within your file explorer.

I'll try to implement #14, #15 and #16 in the same work session, maybe tonight.

**Comment by althonos** [comment]
I added a `-N` / `--new` flag to the CLI, and a `new_only` argument to `InstaLooter.download`, ``InstaLooter.download_pictures` and `InstaLooter.download_videos`. The iteration over medias breaks once the first one is found (so if for instance you have pictures but not videos, and you run instaLooter with `-Nv`, then it won't get the videos older than the most recent picture you have ! keep that in mind).

The *pages* progressbar changes to the *download* one before it is complete, but that shouldn't cause any problem. Try it and tell me if it works well for you ! :smile:
