### ISSUE TITLE
Where is the 'x-instagram-gis' parameter js encryption found? Cut a map of js.

### ISSUE THREAD

**Issue by Wang780968437** [althonos/InstaLooter#163]
Where is the 'x-instagram-gis' parameter js encryption found?
Where is the 'x-instagram-gis' parameter js encryption found?
Cut a map of js Or just copy a piece of js and show it to me.
I didn't find it.thank you.

**Comment by althonos** [comment]
I got all the information here : https://stackoverflow.com/questions/49786980/how-to-perform-unauthenticated-instagram-web-scraping-in-response-to-recent-priv

Since then, the `X-Instagram-GIS` thing does not need the CSRFToken anymore, simply concatenate the `RHX` obtained in the beginning of the session and the parameters as JSON.

**Comment by Wang780968437** [comment]
thank you

**Comment by Youssef1313** [comment]
@althonos , Thanks. It worked for me that it is the md5 of rhx + parameters. But I'm confused of how to know this information by myself. Is that somewhere in the js ? where exactly ?

**Comment by knowledgecomputer2018** [comment]
hi 
where is "rhx_gis" ? in source page instagram "windows.sharedata" not exist???????
thank you very much for help me.
god willing
