### ISSUE TITLE
CRITICAL Query rate exceeded (wait before next run)

### ISSUE THREAD

**Issue by mdmustafizurrahman** [althonos/InstaLooter#171]
## Library version

*What's the installed library version ? Check with `instalooter --version`*:

```
instalooter 2.0.1
```

## Environment

*Describe here your environment, including:*

* *OS*: Linux 4.13.0-38-generic #43~16.04.1-Ubuntu SMP
* *Python version*: Python 2.7.12
* *`setuptools` version if reporting an issue with installation*: pip 8.1.1
* *non-standard Python implementation if any*

## Error description - runtime

*If you have an issue at runtime, include the required information below:*

### Reproducible test case

*Are you using the CLI ? If so, include a command that can be used to re-raise the 
error, with actual arguments anybody can try:*

```
instalooter user instagram

```

### Expected behaviour

Supposed to down all the post made by account named instagram

### Actual behaviour

*What's actually happening ? Leave empty if asking for a new feature*
```
2018-04-26 12:11:57 user instalooter.cli[6045] NOTICE Starting download of `instagram`
2018-04-26 12:11:58 user instalooter.cli[6045] CRITICAL Query rate exceeded (wait before next run)
2018-04-26 12:11:59 user instalooter.cli[2827] NOTICE Terminating 16 remaining workers...
                                                                               Exception KeyError: KeyError(<weakref at 0x7fdbf3b17ba8; to 'TqdmProgressBar' at 0x7fdbf3a67a10>,) in <object repr() failed> ignored

```

**Comment by althonos** [comment]
Since April 2018 and the Cambridge Analytica scandal, Instagram lowered drastically the number of allowed queries to its GraphQL server. Besides, the page size, which used to be of 200 posts, was reduced to 50 posts, which means there needs 4x the queries to scrape the same account.

After some time downloading medias from IG, the server will stop answering, so `instalooter` cannot keep on downloading pictures. When it happens, you must wait some time for the query limiter to reset. All I can do is add an error message to warn about this.

**Comment by Hrxn** [comment]
... "scandal"...

**Comment by althonos** [comment]
> ... "scandal" ...

* *Facebook-gate*
* *very-obvious-company-stealing-personal-data-but-we-all-pretended-not-to-care-for-years*
* *web-developpers-freakout-about-data-scraping-although-their-data-is-public-already*

you name it :wink:

**Comment by mdmustafizurrahman** [comment]
Can you add a wait time of 5 minutes, after making a certain number of queries, then restart querying at the stopped position so that it can complete the download of all media of a profile eventually?

**Comment by althonos** [comment]
@mdmustafizurrahman : the thing is, I don't know the exact number of query Instagram allows, and I don't really have the will to finetune something that's bound to change every now and then.

The reason the program exits when the query rate is exceeded is because I wanted the program to be reactive. You can easily make it run in a loop with a small bash command, such as:
```console
while [ "$(instalooter user ... ...)" != 0 ]; do sleep 300; done
```

**Comment by althonos** [comment]
@mdmustafizurrahman : the thing is, I don't know the exact number of query Instagram allows, and I don't really have the will to finetune something that's bound to change every now and then.

The reason the program exits when the query rate is exceeded is because I wanted the program to be reactive. You can easily make it run in a loop with a small bash command, such as:
```console
$ while [ "$(instalooter user ... ...)" != 0 ]; do sleep 300; done
```

**Comment by distantstar** [comment]
I'm not too sure if commenting on closed/resolved ticket will be helpful. But the above while script may be helpful in restarting the process of instalooter; but it appears instagram is keeping you from downloading more than a certain point and it will not restart from where you ended. Additionally, I have noticed -V does not fetch video only.

**Comment by Hackerpcs** [comment]
@althonos 
What about adding a command line option to make the program wait by its own and then continue, e.g. something like --wait 300 to wait 5 minutes and if limit hasn't been lifted to wait another 5 minutes and so on?

**Comment by NickyFot** [comment]
i keep getting the same error (but no media downloaded at all), is the API closed completely then?

**Comment by daprofessa19** [comment]
This should be treated as a bug. I understand that this is caused by API limits, but instalooter does not retain a memory  of where it stopped during the last run.

Therefore, when you start a new session, you start from the beginning again, and inevitably run into the limit at the same point again.

I have also tried to limit the download by using the --time parameter, but this has no effect.

**Comment by jeanmarctst** [comment]
I agree with daprofessa19, it is not a bug per se, but it is a serious issue that will need to be figured out because threads like this one will keep on piling up.
Any 1000+ posts account triggers this limitation so I suspect it's going to be relatively common.

From what I saw, I suspect the limitation is not only due to the number of requests but maybe also somehow from the amount of data requested. You end up with the limitation varying from one account to the other.

I can also confirm the --time parameter not working. I might be wrong, but maybe Instagram adds up all the data queried (whether you download it or not) and stops you after a certain amount. If you try to download older posts, the program will query all the newer ones first, and you end up downloading nothing.

I believe Althonos you mentioned a possible solution being using another type of request that is not limited.
A great way to implement that would be to either modify the -N command not only to download files newer than the latest one you already have on your computer, but to download every post that doesn't appear in the download folder, newer or older.
Or you could also simply add a new command that does that in addition to -N.
I don't know whether that would be easy or hard to implement, hoping it's not.

But of course, I want to make very clear that your exams are of course the priority Althonos, and as such I wish you very good luck for them, and maybe when they're over you'll have some time to spare and take a look at this :)

**Comment by distantstar** [comment]
- Instalooter will have to fetch the file header, place that into a list, compare the files in your directory, and omit the duplicate from the list.
- One possible issue (I can at least think) is fetching the file header may also count as downloading, and limits from the beginning. 
- If the above isn't the case,  I think we can have instalooter generate all of the file headers into a file in the beginning before anything takes place and save that file as a "master file" of all of the potential files to download. From that file, it can run a diff and download only the files that does not exist in the directory. 

I'm just speculating though. Kind of curious if it will work.

**Comment by namanyayg** [comment]
Was anyone able to make progress or find a solution here? Can something be done via proxies to skip such limits?

**Comment by barraponto** [comment]
I don't think instalooter needs to download the file header. AFAIK post ids are unique and immutable, so instaloader either fully downloaded the files for that post or it didn't -- we can keep track of that. Of course, it still needs to paginate as well to get the full list of posts.
