### ISSUE TITLE
Getting URLs of multi image posts in the JSON file?

### ISSUE THREAD

**Issue by wrybread** [althonos/InstaLooter#178]
I think when searching for details about a post that has multiple images, only the first image is contained in the JSON file.  The multiple images are however downloaded correctly, they're just absent in the JSON file about that post.

Is it an easy fix to make the multiple images have entries in the JSON file?

**Comment by althonos** [comment]
Hi @wrybread , 

I suppose you're simply iterating on posts, which is why you don't see multiple images. You have to use the `get_post_info` method to query extended metadata for multi-posts, which will contain all the links.

For instance:
```python
looter = instalooter.looters.ProfileLooter("...")
for media in looter.medias():
    if media['__typename'] == "GraphSidecar":
        extended = looter.get_post_info(media["shortcode"])
```

Then your `extended` dictionary will contain a lot of additional resources, including links to all the posts.
