### ISSUE TITLE
[Feature Request] Display profile name with download / Skip missing or bad profiles

### ISSUE THREAD

**Issue by JPNYC81** [althonos/InstaLooter#185]
Other than for informational purposes when downloading, would help with troubleshooting "CRITICAL - ProfilePage" issues and removing dead/removed profiles from the queue.

And on that note, if there is a "ProfilePage" issue thrown, skipping over it on to the next profile would be preferred than killing the entire queue.

**Comment by althonos** [comment]
Actually I was logging that information, but I forgot to setup the `instalooter.batch` logger in the CLI module which meant no message was being displayed. This should be fixed in `v2.0.4`.

Batch runner will only display an error message when a job raises an exception, and then start the next job in queue.
Batch mode will not display an error mess
