### ISSUE TITLE
Setting up the batch file

### ISSUE THREAD

**Issue by Naponoel** [althonos/InstaLooter#223]
It's quite dumb question but if someone would take time to explain how to setup batch file and use it with program... Thanks

**Comment by jpegcoma** [comment]
Structure of you batch.ini file (you can make it with wordpad):
[first section]
username = login_to_your_acc
password = pass_to_your_acc
num-to-dl = 5    -> max number of photos to download
New = True        -> take only new photos (meaning, since the last loot)
template = {username}.{datetime}    -> the way you want you downloaded file names to look like
users =     
    user1 you want to loot from :  path to the folder where photos will be saved 
    (path like - C:\Users\your_user_name\insta_grab\photos_from_acc\user1, the folder will be created)
    user2 you want to loot from :  path to the folder where photos will be saved
    user3 you want to loot from :  path to the folder where photos will be saved
[second section]
username = .... (if you don't pass it here, looter will try to use the ones from the previous section)
password = .... (if you don't pass it here, looter will try to use the ones from the previous section)
num-to-dl = 5
New = True 
template = {username}.{datetime}
users =   
    user4 you want to loot from :  path to the folder where photos will be saved
    user5 you want to loot from :  path to the folder where photos will be saved
    user6 you want to loot from :  path to the folder where photos will be saved

You need to have 4 spaces before each line of user you want to loot from.
Plus, check other commands in the Batch section of looter - https://instalooter.readthedocs.io/en/latest/batch.html

Put this file in some folder and in command line write: instaLooter batch /path/to/your/batch.ini

hope it helps

**Comment by Naponoel** [comment]
Thanks a lot! Got it working!
