### ISSUE TITLE
fail to download all pictures/videos in one post

### ISSUE THREAD

**Issue by miser555** [althonos/InstaLooter#230]
Hi,
I'm using the latest version, and when I try to download all posts for particular IG accounts, InstaLooter does a pretty good job, but it still doesn't download all pictures/videos if the post contains more than one picture (sometimes it downloads only two pictures or a picture and a video out of 5 or 6 pictures and videos in one post). Any solutions?

Thanks!

**Comment by althonos** [comment]
Can you give me a link to an example post I could reproduce this with ?

**Comment by miser555** [comment]
when I removed the -T flag, it worked. other users stated the same.
https://github.com/althonos/InstaLooter/issues/142#issuecomment-450654520

see this as well: https://github.com/althonos/InstaLooter/issues/142#issuecomment-450546988

I want to use this: -T {datetime}.{username} as I wrote a script to download posts of many accounts, and I want the files to be saved using this format. The solution to download all posts was removing the -T flag. Any thoughts?


thank you.

**Comment by althonos** [comment]
This is the expected behaviour: when downloading a post that has several images with `-T {datetime}.{username}`, since all images were posted at the same time by the same user, they will all be written to the same file. Use `-T {datetime}.{username}.{id}` or `-T {datetime}.{username}.{code}` to make sure the generated filenames are unique.

**Comment by miser555** [comment]
I should've thought of that. Terrific. Thank you!
