### ISSUE TITLE
How to get random user name, etc?

### ISSUE THREAD

**Issue by mrgloom** [althonos/InstaLooter#24]
1) Is there any way to get random user name or full list of instagram users?
3) Is there any way to get user subscribers or users that current user subscribed to?
4) Is there any way to get also photos from other users on those current user is marked?
5) Is there any way to get list of users from comments of current user?

**Comment by althonos** [comment]
No for all, since this you'd have to get access to the Instagram DB, which is locked if you're not using the API :(

**Comment by mrgloom** [comment]
But I can see comments under photos via browser, so I think that is possible without API.
Same for users tagged on photos.

**Comment by althonos** [comment]
Well, what you can get is the list of users that commented a picture/video, knowing what picture/video to look at. You can also get the list of user tagged in a caption, since you have access to each picture and video caption. 

What you asked, getting all the photos on which the user is marked / that user commented, is virtually impossible.

**Comment by althonos** [comment]
Here you can generate a set of users that commented on pictures of `targetprofile`. Replace 'comments' by 'likes' and you'll have a set of users that liked at least one picture of `targetprofile`

```python
from instaLooter import InstaLooter
looter = InstaLooter(profile="targetprofile")

users = set()
for media in looter.medias(with_pbar=True):
    post_info = looter.get_post_info(media['code'])
    for comment in post_info['comments']['nodes']:
        user = comment['user']['username']
        users.add(user)
```

Be warned this'll take quite a long time, because the post page of all picture / videos must be downloaded and parsed.

**Comment by mrgloom** [comment]
Thanks, I checked it and it works. What about users marked on photos?

**Comment by althonos** [comment]
Set of users tagged in pictures of a particular user:
```python
from instaLooter import InstaLooter
looter = InstaLooter(profile="targetprofile")

users = set()
for media in looter.medias(with_pbar=True):
    post_info = looter.get_post_info(media['code'])
    for usertag in post_info['usertags']['nodes']:
        user = usertag['user']['username']
        users.add(user)
```
