### ISSUE TITLE
I can't download

### ISSUE THREAD

**Issue by finsther** [althonos/InstaLooter#254]
hello, since version 2.4 I can not download any instagram post, it does not send any error, when I run the instalooter instagram user command, the cursor just keeps blinking :disappointed:

**Comment by SR-G** [comment]
Same problem here ...

**Comment by althonos** [comment]
Hi ! I assume this is caused by the new user-agent detection feature, which attempts to open your usual webbrowser to detect its `User-Agent` header: if running in docker like @SR-G, it is likely this is causing trouble since it waits for you to close a browser you don't have any access to.

As a workaround, you can create a file named `~/.cache/instalooter/2.4.0/user-agent.txt` containing a user-agent string.

**Comment by hashark** [comment]
Hi @althonos, I had the same issue running with python 2.7 on ubuntu (with no docker)

**Comment by finsther** [comment]
hi @althonos, i'm running with python 3.4 and 3.5 with same issue on ubuntu 18 with no docker like @hashark .
even, in the previous version I could download using Termux for android without any problem

**Comment by SR-G** [comment]
Hey again. I can confirm that @althonos suggestion is part of the solution.

There is just one additional issue : the user-agent.txt file has to be written without any end-of-line character, otherwise you'll get the error : 

```
2019-07-08 18:52:38 2af6e991f821 instalooter.cli[338] CRITICAL Invalid header value b'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17\n'
```

So i had to use : 

```
echo -e "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0\c" > user-agent.txt
```

My dockerfile for reference :  

```
FROM	<base_image_with_python3>
ENTRYPOINT	["/usr/local/bin/instalooter"]
CMD	["-h"]
VOLUME	/data
RUN	pip3 install instaLooter
ADD	user-agent.txt /root/.cache/instalooter/2.4.0/
```

Now it seems to be working again (but to be very, very slow - i don't remember if it was already so slow before, as i'm running it by cron most of the time) : 

```
2019-07-08 18:57:15 154a67885c96 instalooter.cli[1] NOTICE Starting download of `<account_to_download>`
2019-07-08 18:59:24 56e6c7fc8e79 instalooter.cli[1] SUCCESS Downloaded 3 posts.
  2%|████                                                                                                                                                                                                   | 3/149 [00:01<02:06,  1.16it/s]
```

**Comment by finsther** [comment]
> echo -e "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0\c" > user-agent.txt


man thank you very much for your instructions, now I can download again, I do not use docker, but still just create the file with the agent configuration and problem solved
