### ISSUE TITLE
[Bug] Does not download videos

### ISSUE THREAD

**Issue by rsxgti** [althonos/InstaLooter#31]
InstaLooter does not seem to download any videos.

**Comment by RPSPandora** [comment]
With -v option ?
I've downloaded video normaly with .mp4 extension

On Feb 3, 2017 5:01 AM, "rsxgti" <notifications@github.com> wrote:

InstaLooter does not seem to download any videos.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/althonos/InstaLooter/issues/31>, or mute the thread

**Comment by althonos** [comment]
Closing.
