### ISSUE TITLE
[Bug] Time parameter not working?

### ISSUE THREAD

**Issue by Bangaio64** [althonos/InstaLooter#35]
Python 3.6.0 on Windows 7 x64

`>Instalooter nintendo --time 2017-02-05:2017-02-09 -q`
`←[35m23:14:38←[0m - ←[33mWARNING←[0m - ←[39mNo medias found.←[0m`

But `thisweek` works correctly.

**Comment by althonos** [comment]
The `time` parameter format as stated in the help must be `start:stop`, with `stop` older than `start`. So in this case, the correct command is: `instaLooter nintendo --time 2017-02-09:2017-02-05`, which I checked downloads 3 pictures.

(I'll push a fix so that the formatting of warnings is nicer on Windows though ;D ).

**Comment by Bangaio64** [comment]
It sounds counter-intuitive to me to put the later date first, but I guess it does make sense considering instagram shows the latest pictures first. Thanks for the reply.

**Comment by althonos** [comment]
Yes I know, I actually had to double check myself but that made sense when I implemented it, i had to make a choice at some point :)

**Comment by cyrusclarke** [comment]
is there an issue where there is hashtag that is too generic? the time parameter seems to work fine with niche hashtags (nintendo, magicmouse etc.) but with something super generic like "happy" it returns no media found. if i run the same query without --time i get a lot of results.

**Comment by althonos** [comment]
@cyrusclarke : Nope, I'll open an issue.
