### ISSUE TITLE
[Feature request] Download Multi Photo/Video Posts

### ISSUE THREAD

**Issue by verafide** [althonos/InstaLooter#39]
In case anyone didn't know (I didn't until today) [Instagram recently introduced this feature.](http://blog.instagram.com/post/157572774352/170222-multiple)  

Currently what InstaLooter does with a multi post is just download the first image downscaled. Here is an example of one of these posts - https://www.instagram.com/p/BRHecUuFhPl/

**Comment by althonos** [comment]
Didn't know that, but it seems very straightforward to fix ! 
The page you sent me has an additional key compared to usual pages: "edge_sidecar_to_children" !
So that makes it really easy to find if a page is multipost or not. And even better : this attribute stores the links to all the pictures of the multipost ! 

I'll be pushing a patch quickly, since this seems like a 20mn job.

**Comment by althonos** [comment]
Implemented in version 0.7.0.

I had some troubles to get the `-n` and `-v` flags to work consistently, but I managed to do it. Just note that **nothing will differentiate medias coming from a multipost** once they are downloaded, and that **the medias from a multipost may not be downloaded alltogether if the `-n` flag is used**.
