### ISSUE TITLE
[Bug] Hashtag not working without credentials

### ISSUE THREAD

**Issue by paddoum** [althonos/InstaLooter#45]
Hello,

Thanks for this app.

When I use : instaLooter hashtag sunset

I get following error message
12:33:01 - WARNING - Could not find page of user: hashtag
12:33:01 - WARNING - No medias found.

It seems that I cannot get pictures based on a specific hashtag.

Do I do something wrong?

**Comment by althonos** [comment]
Since early March 2017, **instagram made the hashtag exploring a private feature**. This means you'll have to have an account and login with your credentials to be able to use the `hashtag` feature. This is linked to a change in their service, not to my code unfortunately. I'll add a disclaimer somewhere.

**Comment by dlancho** [comment]
I get this issue even with a correct login information.

python -m instaLooter hashtag sunset -c login:password
←[35m15:10:50←[0m - ←[32mSUCCESS←[0m - ←[39mLogged in.←[0m
15:10:50 - WARNING - Could not find page of user: hashtag
15:10:50 - WARNING - No medias found.

**Comment by althonos** [comment]
Adding a path to a directory is mandatory when using hashtag, else InstaLooter thinks you're trying to store a profile called "hashtag" info a directory called "sunset"... That's a docopt limitation.

**Comment by althonos** [comment]
**Good news**: Instagram made tag exploring public back again. Closing the issue since this works just fine now.
