### ISSUE TITLE
[Bug] Fail to retrieve caption for videos

### ISSUE THREAD

**Issue by VasiliPupkin256** [althonos/InstaLooter#57]
On most recent version 0.9.3 using a metadata `-m` switch it fails to retrieve caption attribute and throw errors.

Can be reproduced by this command:
`instalooter -v -m awwwwshoot_ob`

> Traceback (most recent call last):
>   File "...\lib\threading.py", line 911, in _bootstrap_innerself.run()
>   File "...\lib\site-packages\instaLooter\worker.py", line 47, in runself._download_photo(media)
>   File "...\lib\site-packages\instaLooter\worker.py", line 97, in _download_photoself._add_metadata(photo_name, media)
>   File "...\lib\site-packages\instaLooter\worker.py", line 81, in _add_metadatapiexif.ExifIFD.UserComment: metadata.get('caption', '').encode('utf-8'),
> AttributeError: 'NoneType' object has no attribute 'encode'

This part of code (worker.py, line 81) has also brought to light some weird refactoring bug. The idea of the statement was obviously to return '' if there was no caption in `metadata` dictionary but for some reason the `caption` key was associated with None value already. It should test it for None and not rely on `get` method default return value. Or the `caption` key shouldn't be added to the metadata dictionary (or set to '' ) in _sidecar_to_media method of core.py if no caption was found in media.

**Comment by althonos** [comment]
Indeed, I have to admit I did a lazy job when fixing attributes for the multiple image posts. This led to using the `dict.get` method in some places in order to prevent KeyErrors from happening, but because of this some None values are added to the media dictionaries.

First of all I have to fix the caption fetching, since IG moved the caption of a post to another location. Then it may be necessary to also update the buggy piece of code you're mentioning here.

**Comment by althonos** [comment]
I fixed it, caption should now be properly extracted, I added an acceptance test about that, and fixed the issue causing None to be added to the metadata dictionaries.
