### ISSUE TITLE
Post option always downloads same post

### ISSUE THREAD

**Issue by sammoth** [althonos/InstaLooter#61]
When I run the command to download a post, eg.

`$ instaLooter post "https://www.instagram.com/p/BTbIXWmAybZ/"`

an unrelated set of images are downloaded:

![](http://i.imgur.com/Ac9tChP.png)

In fact whichever post I try to download, this same set of images is downloaded instead

**Comment by althonos** [comment]
Ahah yeah that's a known bug caused by docopt, instaLooter thinks you want to download the pictures from a user called `post` in a directory called `https://....`. Just add `.` after the command (force the current directory) and it will work.
I'll add a fix to force docopt to quit when no directory is given when downloading hashtag or videos.
