### ISSUE TITLE
InstaLooter may not be downloading the highest quality version of images

### ISSUE THREAD

**Issue by sammoth** [althonos/InstaLooter#62]
If I download the following image with instalooter: https://www.instagram.com/p/BTehD--Ah8O/

the image I get back is 127.4KB. I can get the same image at the following url, which is the one loaded on the image page for me:

https://scontent-lht6-1.cdninstagram.com/t51.2885-15/e35/18162141_1877705662453451_3389275825621696512_n.jpg

However by removing the "/e35" part of the URL I get back an image that's 144KB. I'm not quite sure what the e35 is doing, the other URL parts that are used by Instagram are more obvious like sh0.08 (sharpening) and s000x000 (resize). Do you think that the /eXX/ part of the URL needs removing before instaLooter retrieves images?

**Comment by althonos** [comment]
I have no idea, since on some pictures it does not change anything at all to remove the /eXX/ part. Weird. I'll check if I can remove that part as well with the regex that preprocesses media URLs.

**Comment by althonos** [comment]
InstaLooter will now use the smallest working URL to download pictures, e.g. https://scontent-lht6-1.cdninstagram.com/t51.2885-15/e35/18162141_1877705662453451_3389275825621696512_n.jpg will be sanitized as https://scontent-lht6-1.cdninstagram.com//18162141_1877705662453451_3389275825621696512_n.jpg before download.

Notice the `//`, they are intentional as a single slash cause the server to error when requesting the resource.
