### ISSUE TITLE
[Bug] Only first post in multiposts are downloaded

### ISSUE THREAD

**Issue by aaasddd** [althonos/InstaLooter#70]
When I run for example 

`instaLooter  indiak8 D:\Pictures\Instagram\\indiak8 --get-videos -T "{username}.{datetime}" -N `

I will only download the first photo of the multiposts. Are there any fix to this?

**Comment by althonos** [comment]
Are you using latest release (`0.9.7` or `0.9.8`, latest fix shouldn't change anything to your issue)

I suspect this comes from the `-N` flag, that causes InstaLooter to stop downloading a multipost because of the date. Does it still happen without it ?

**Comment by aaasddd** [comment]
Yes, it's still happening. The only time it downloads all the multiposts is when I remove `{username}.{datetime}`, so I reckon it has something to do with the date.

**Comment by aaasddd** [comment]
After reading the documentation I included `{id}` and it worked, along with `-N` too. 

Also, when I use `-m` where is the metadata stored? Because the title of the image is unchanged and there are no additional files added containing caption, etc.

**Comment by althonos** [comment]
Aaaah yeah of course, silly me, I will update the documentation since with multiposts `{datetime}` is not unique anymore.

For the metadata, they are added to [EXIF tags](https://en.wikipedia.org/wiki/Exif), so you can see them with picture viewers supporting them (see the full list [here](https://en.wikipedia.org/wiki/Comparison_of_image_viewers#Additional_features), look for EXIF in the metadata column).
