### ISSUE TITLE
[Feature request] Download periodically

### ISSUE THREAD

**Issue by VirtualEvan** [althonos/InstaLooter#85]
I think that checking periodically for new posts in a profile or hashtag  would be a nice feature to implement. Specifying as a parameter the time lapse for each check.

**Comment by polyzen** [comment]
See #49 if you're on a UNIX-like system.

**Comment by VirtualEvan** [comment]
Yes, I am use cron right now, but its a bit dirty using pew/virtualenv and managing the output manually

**Comment by althonos** [comment]
I'm keen on following the UNIX philosophy here, a tool for each job. If InstaLooter were to manage itself as a daemon internally, I'm not sure it would be as easy as it is now to use, and maybe harder to make cross-platform.

Still, I can try to enhance the ouput / usage so that it merges with cron better. Why do you have to trouble yourself with virtualenv ?

**Comment by VirtualEvan** [comment]
I just thought that it would be a nice feature and wanted to give the idea, but I get your point.
And I am actually using pew, just for organizing myself within different projects.

**Comment by althonos** [comment]
I added a page to the documentation about this issue, so I'll be closing it, yet feel free to comment if you feel something is lacking. The page is available at http://instalooter.readthedocs.io/en/latest/cron.html
