### ISSUE TITLE
Issue downloading hashtag with metadata

### ISSUE THREAD

**Issue by kurtmaia** [althonos/InstaLooter#9]
Hi,
 
I am trying to download a hashtag with metadata added, but I keep getting the same error related to 'full_name'

my input: instaLooter hashtag fluoxetine ./Data/ --add-metadata -n 200 

the output:
...
  File "/Library/Python/2.7/site-packages/instaLooter.py", line 96, in _add_metadata
    piexif.ImageIFD.Artist: "Image creator, {}".format(self.owner.metadata['full_name']),
KeyError: 'full_name'

**Comment by althonos** [comment]
Hi, thanks for feedback.
Since the metadata page doesn't work the same way the profile page does, pictures and video have less metadata associated with them, and don't have the actual full name of the media owner. I added a method to fetch that information, but I forgot to change the code for metadatas. I'll patch as quick as possible.

**Comment by althonos** [comment]
I pushed a fix on the Github and released a PyPI version 0.3.1 for this.
I'm closing for now, I tested it and it worked for me but don't hesitate to open the issue again if needed.
